name: Update WakaTime stats

on:
  workflow_dispatch:
  schedule:
    # Every day
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update WakaTime DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: all_time
